# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0ca3658eb23546f357c545c0dd2e03e94983ccce8fbd32e3999304c2b96cbff7b2aeba68f06951cafb8460f2d32db83e3784a000ebb950510a5f566b91929a0

test:
  secret_key_base: f56787517556b0ccaa0290b5a42e1624c7383165e05d14964017f662a516193e866a9b716caf51c34515ce7b6b930ca1c5a4b74b475f160dd4e88c7301468ad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
